# Generated by Django 5.1.1 on 2024-10-12 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("fatherName", models.CharField(max_length=50)),
                ("motherName", models.CharField(max_length=50)),
                ("spouseName", models.CharField(max_length=50, null=True)),
                ("mobileNumber1", models.CharField(max_length=15)),
                ("mobileNumber2", models.CharField(max_length=15, null=True)),
                ("dateOfBirth", models.DateField()),
                ("gender", models.CharField(max_length=50)),
                ("bloodGroup", models.CharField(max_length=50, null=True)),
                ("emailId", models.EmailField(max_length=50, null=True)),
                ("currentAddress1", models.CharField(max_length=250, null=True)),
                ("currentAddress2", models.CharField(max_length=250, null=True)),
                ("currentCity", models.CharField(max_length=50)),
                ("currentDistrict", models.CharField(max_length=50)),
                ("currentState", models.CharField(max_length=50)),
                ("currentCountry", models.CharField(max_length=50)),
                ("currentPinCode", models.CharField(max_length=6)),
                ("permanentAddress1", models.CharField(max_length=250, null=True)),
                ("permanentAddress2", models.CharField(max_length=250, null=True)),
                ("permanentCity", models.CharField(max_length=50, null=True)),
                ("permanentDistrict", models.CharField(max_length=50)),
                ("permanentState", models.CharField(max_length=50)),
                ("permanentCountry", models.CharField(max_length=50)),
                ("permanentCode", models.CharField(max_length=6)),
                ("highestQualification", models.CharField(max_length=100, null=True)),
                ("instituteName", models.CharField(max_length=50, null=True)),
                ("stream", models.CharField(max_length=50, null=True)),
                ("passedOutYear", models.IntegerField(null=True)),
                ("skills", models.CharField(max_length=50, null=True)),
                ("jobCategory", models.CharField(max_length=50, null=True)),
                ("companyName", models.CharField(max_length=50, null=True)),
                ("jobDesignation", models.CharField(max_length=50, null=True)),
                ("companyLocation", models.CharField(max_length=50, null=True)),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "new_detail",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
            },
        ),
    ]
