# Generated by Django 5.1.1 on 2024-10-19 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=50)),
                ("middleName", models.CharField(blank=True, max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("fatherName", models.CharField(max_length=50)),
                ("motherName", models.CharField(max_length=50)),
                ("spouseName", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mobile1",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("mobile2", models.CharField(blank=True, max_length=15, null=True)),
                ("dateOfBirth", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=10)),
                ("bloodGroup", models.CharField(blank=True, max_length=10, null=True)),
                ("emailId", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "currentAddress1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "currentAddress2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("currentCity", models.CharField(max_length=50)),
                ("currentDistrict", models.CharField(max_length=50)),
                ("currentState", models.CharField(max_length=50)),
                ("currentCountry", models.CharField(max_length=50)),
                ("currentPinCode", models.CharField(max_length=6)),
                (
                    "permanentAddress1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "permanentAddress2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "permanentCity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("permanentDistrict", models.CharField(max_length=50)),
                ("permanentState", models.CharField(max_length=50)),
                ("permanentCountry", models.CharField(max_length=50)),
                ("permanentPinCode", models.CharField(max_length=6)),
                (
                    "highestQualification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instituteName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("stream", models.CharField(blank=True, max_length=50, null=True)),
                ("passedOutYear", models.IntegerField(blank=True, null=True)),
                ("skills", models.CharField(blank=True, max_length=250, null=True)),
                ("jobCategory", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "companyName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jobDesignation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("companyLocation", models.CharField(max_length=50)),
                ("annualIncome", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "new_detail",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
            },
        ),
    ]
