# Generated by Django 5.1.1 on 2024-10-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("firstName", models.CharField(max_length=255)),
                ("middleName", models.CharField(blank=True, max_length=255, null=True)),
                ("lastName", models.CharField(max_length=255)),
                ("fatherName", models.CharField(max_length=255)),
                ("mothersName", models.CharField(max_length=255)),
                ("spouseName", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile1", models.BigIntegerField(primary_key=True, serialize=False)),
                ("mobile2", models.BigIntegerField(blank=True, null=True)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=255)),
                ("bloodGroup", models.CharField(max_length=3)),
                ("Email", models.EmailField(max_length=255)),
                ("commDoorNo", models.CharField(max_length=100)),
                ("commStreetName", models.CharField(max_length=255)),
                ("commArea", models.CharField(max_length=255)),
                ("commCity", models.CharField(max_length=100)),
                ("commDistrict", models.CharField(max_length=100)),
                ("commState", models.CharField(max_length=100)),
                ("commCountry", models.CharField(max_length=100)),
                ("commPincode", models.CharField(max_length=20)),
                ("permDoorNo", models.CharField(max_length=100)),
                ("permStreetName", models.CharField(max_length=255)),
                ("permArea", models.CharField(max_length=255)),
                ("permCity", models.CharField(max_length=100)),
                ("permDistrict", models.CharField(max_length=100)),
                ("permState", models.CharField(max_length=100)),
                ("permCountry", models.CharField(max_length=100)),
                ("permPincode", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "new_detail",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("father_name", models.CharField(blank=True, max_length=30)),
                ("mother_name", models.CharField(blank=True, max_length=30)),
                ("spouse_name", models.CharField(blank=True, max_length=30)),
                ("mobile1", models.CharField(max_length=15)),
                ("mobile2", models.CharField(blank=True, max_length=15)),
                ("country_code1", models.CharField(max_length=5)),
                ("country_code2", models.CharField(default="+91", max_length=5)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("role", models.CharField(default="user", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
